create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats (id) on delete cascade,
  owner_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.chats enable row level security;
alter table public.messages enable row level security;

drop policy if exists "chats_select_own" on public.chats;
create policy "chats_select_own"
on public.chats for select
using (auth.uid() = owner_id);

drop policy if exists "chats_insert_own" on public.chats;
create policy "chats_insert_own"
on public.chats for insert
with check (auth.uid() = owner_id);

drop policy if exists "chats_delete_own" on public.chats;
create policy "chats_delete_own"
on public.chats for delete
using (auth.uid() = owner_id);

drop policy if exists "messages_select_own" on public.messages;
create policy "messages_select_own"
on public.messages for select
using (
  exists (
    select 1
    from public.chats
    where chats.id = messages.chat_id
      and chats.owner_id = auth.uid()
  )
);

drop policy if exists "messages_insert_own" on public.messages;
create policy "messages_insert_own"
on public.messages for insert
with check (
  auth.uid() = owner_id
  and exists (
    select 1
    from public.chats
    where chats.id = messages.chat_id
      and chats.owner_id = auth.uid()
  )
);

drop policy if exists "messages_delete_own" on public.messages;
create policy "messages_delete_own"
on public.messages for delete
using (
  exists (
    select 1
    from public.chats
    where chats.id = messages.chat_id
      and chats.owner_id = auth.uid()
  )
);
